require 'spec_helper'

describe 'collectd::plugin::aggregation', :type => :class do

  context ':ensure => present, default params' do
    let :facts do
      {:osfamily => 'RedHat'}
    end
    it 'Will create /etc/collectd.d/10-aggregation.conf' do
      should contain_file('aggregation.load').with({
        :ensure  => 'present',
        :path    => '/etc/collectd.d/10-aggregation.conf',
        :content => /\#\ Generated by Puppet\nLoadPlugin aggregation\n\n/,
      })
    end
  end
end
  

